### PR TITLE
Updates README with config info for Devise models to produce callback routes

### PR DESCRIPTION
**Pull request by sunsheeppoplar**
Thanks again for the gem in the first place - it's been very helpful today!

### CODE REVIEW

**Comment by swrobel** [comment]
Hm, I haven't needed to add the config to `user.rb` to get it to work in my app... Any idea why you had to?

**Comment by sunsheeppoplar** [comment]
Not totally sure. I could reproduce a repo for you?

**Comment by isaacsanders** [comment]
@sunsheeppoplar @swrobel Have you two reached a consensus on this topic?

**Comment by swrobel** [comment]
@sunsheeppoplar I'm on Devise 4.4.3, Omniauth 1.8.1, Omniauth-OAuth2 1.5.0

**Comment by sunsheeppoplar** [comment]
@swrobel What version of Rails?

**Comment by swrobel** [comment]
5.2.0.rc2

**Comment by isaacsanders** [comment]
So is the consensus on this Documentation that it is valid?

**Comment by swrobel** [comment]
@isaacsanders @sunsheeppoplar it's probably Devise best-practice, so it seems fine to me. I only have `:omniauthable, omniauth_providers: [:facebook]` but then again, I don't actually sign users in with Stripe, just use the oauth flow to get tokens.

**Pull request merged**
