### PR TITLE
Overwrite callback_url so that it doesn't include query params since Stripe doesn't support them

### PR DESCRIPTION
**Pull request by ryanclark2**
- Addresses: https://github.com/isaacsanders/omniauth-stripe-connect/issues/48

### CODE REVIEW

**Comment by isaacsanders** [comment]
@ryanclark2 Can you force push and remove the addition of the `.idea` workspace? After that, let me know, and I would be happy to merge and release a new change.

**Comment by ryanclark2** [comment]
@isaacsanders Done! Thought I'd killed all of that stuff.

**Comment by langalex** [comment]
also just stumbled across this problem (#48). can this PR be merged and released?

**Comment by isaacsanders** [comment]
@langalex thanks for the ping. I will merge and release later this morning.

**Comment by sunsheeppoplar** [comment]
Was there a reason this was never merged?

**Comment by isaacsanders** [comment]
I likely got distracted. I haven’t worked with this for my day job in 6 years, so I don’t have a lot of time to spend on it.

**Comment by swrobel** [comment]
@isaacsanders I'm happy to take over maintenance of this gem. Just let me know if you're interested & we can discuss.

**Comment by swrobel** [comment]
@isaacsanders ping!

**Comment by isaacsanders** [comment]
@swrobel I appreciate the ping. Sorry to have not responded to your previous message. Feel free to email me if you are still interested, we can chat.

**Pull request merged**
