### PR TITLE
Update stripe_connect.rb

### PR DESCRIPTION
**Pull request by homakov**
Fixing csrf vulnerability.

### CODE REVIEW

**Comment by bhaity** [comment]
@isaacsanders @homakov what's the status on merging this ?

**Comment by isaacsanders** [comment]
I feel like this was released in v2.7.0...

**Comment by isaacsanders** [comment]
I received an email from Stripe's Security team to fix this, and it was all said and done before I saw @homakov's PR. Thanks for your contribution, @homakov.

**Comment by isaacsanders** [comment]
I am kind of geeking out that you even put a PR in on one of my projects.

**Pull request closed without merging**
